
dependencies {
    api project(":eventuate-client-java-event-handling")
    api project(":eventuate-client-java-jdbc-common")
    api project(":eventuate-client-java-common-impl-events")
    api "com.h2database:h2:$h2Version"
    api "io.eventuate.common:eventuate-common-jdbc:$eventuateCommonVersion"
}
tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
