newcdcservice:
  build: ./new-cdc/eventuate-local-java-cdc-sql-service
  ports:
    - "8099:8080"
  links:
    - mysqlbinlogpipeline
    - postgrespollingpipeline
    - postgreswalpipeline
    - kafka
    - zookeeper
  environment:
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATE_CDC_PIPELINE_PROPERTIES: >
      [{"type":"eventuate-local",
      "reader":"reader1"},
      {"type":"eventuate-local",
      "reader":"reader2"},
      {"type":"eventuate-local",
      "reader":"reader3"}]
    EVENTUATE_CDC_PIPELINE_READER_PROPERTIES: >
      [{"type":"mysql-binlog",
      "name":"reader1",
      "dataSourceUrl":"jdbc:mysql://${DOCKER_HOST_IP}:3306/eventuate",
      "dataSourceUserName":"mysqluser",
      "dataSourcePassword":"mysqlpw",
      "dataSourceDriverClassName":"com.mysql.jdbc.Driver",
      "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/1",
      "mySqlBinLogClientName":"DbLog1",
      "cdcDbUserName":"root",
      "cdcDbPassword":"rootpassword"},
      {"type":"polling",
      "name":"reader2",
      "dataSourceUrl":"jdbc:postgresql://${DOCKER_HOST_IP}/eventuate",
      "dataSourceUserName":"eventuate",
      "dataSourcePassword":"eventuate",
      "dataSourceDriverClassName":"org.postgresql.Driver",
      "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/2"},
      {"type":"postgres-wal",
      "name":"reader3",
      "dataSourceUrl":"jdbc:postgresql://${DOCKER_HOST_IP}:5433/eventuate",
      "dataSourceUserName":"eventuate",
      "dataSourcePassword":"eventuate",
      "dataSourceDriverClassName":"org.postgresql.Driver",
      "mySqlBinLogClientName":"DbLog2",
      "leadershipLockPath":"/eventuatelocal/cdc/leader/pipeline/3"}]
