

deployUrl=file:///Users/cer/.m2/testdeploy
eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://snapshots.repositories.eventuate.io/repository

dockerComposePluginVersion=0.17.7
springBootVersion=4.1.1

eventuateUtilVersion=0.20.0.BUILD-SNAPSHOT
eventuateCommonVersion=0.22.0.BUILD-SNAPSHOT
eventuateMessagingKafkaVersion=0.22.0.BUILD-SNAPSHOT
eventuatePluginsGradleVersion=0.15.0.BUILD-SNAPSHOT
junitVersion=6.0.3
junitPlatformLauncherVersion=6.0.3
kafkaClientVersion=4.2.1
eventuateCommonImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateMessagingKafkaImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateCdcImageVersion=0.20.0.BUILD-SNAPSHOT

removeContainers=true
micronautVersion=2.4.1
mockitoVersion=5.23.0
slf4jVersion=2.0.18
commonsLang3Version=3.20.0
h2Version=2.4.240
mysqlConnectorVersion=9.7.0
postgresqlVersion=42.7.13
mssqlJdbcVersion=13.4.0.jre11
hikariCpVersion=7.0.2
jakartaAnnotationVersion=3.0.0

version=0.45.0-SNAPSHOT
