

deployUrl=file:///Users/cer/.m2/testdeploy
eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://snapshots.repositories.eventuate.io/repository

dockerComposePluginVersion=0.17.7
springBootVersion=3.4.7

eventuateUtilVersion=0.19.0.RELEASE
eventuateCommonVersion=0.21.0.RELEASE
eventuateMessagingKafkaVersion=0.21.0.RELEASE
rxJavaVersion=1.1.5
eventuatePluginsGradleVersion=0.14.0.RELEASE
junitVersion=5.12.2
junitPlatformLauncherVersion=1.12.2
kafkaClientVersion=3.1.1
eventuateCommonImageVersion=0.21.0.RELEASE
eventuateMessagingKafkaImageVersion=0.21.0.RELEASE
eventuateCdcImageVersion=0.19.0.RELEASE

removeContainers=true
micronautVersion=2.4.1
mockitoVersion=4.11.0

version=0.44.0-SNAPSHOT
