package io.eventuate.local.unified.cdc.pipeline.dblog.common.configuration;

import io.eventuate.local.unified.cdc.pipeline.common.configuration.CommonCdcDefaultPipelinePropertiesConfiguration;
import io.eventuate.local.unified.cdc.pipeline.dblog.common.CommonDbLogCdcPipelineProperties;
import org.springframework.context.annotation.Configuration;

@Configuration
public class CommonDbLogCdcDefaultPipelinePropertiesConfiguration extends CommonCdcDefaultPipelinePropertiesConfiguration {

  protected void initCommonDbLogCdcPipelineProperties(CommonDbLogCdcPipelineProperties commonDbLogCdcPipelineProperties) {
    commonDbLogCdcPipelineProperties.setBinlogConnectionTimeoutInMilliseconds(eventuateConfigurationProperties.getBinlogConnectionTimeoutInMilliseconds());
    commonDbLogCdcPipelineProperties.setDbHistoryTopicName(eventuateConfigurationProperties.getDbHistoryTopicName());
    commonDbLogCdcPipelineProperties.setMaxAttemptsForBinlogConnection(eventuateConfigurationProperties.getMaxAttemptsForBinlogConnection());
    commonDbLogCdcPipelineProperties.setMySqlBinLogClientName(eventuateConfigurationProperties.getMySqlBinLogClientName());
  }
}
